name: Add rewrites to vercel config
on:
  push:
    branches: [ main, caleb/vercel-auto-config ]
  pull_request:
    branches: [ main, caleb/vercel-auto-config ]
  repository_dispatch:
    types:
      - webhook
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CONTENTFUL_WEBSITE_SPACE_ID: ${{secrets.GH_PACKAGES_TOKEN}}
      CONTENTFUL_WEBSITE_ACCESS_TOKEN: ${{secrets.GH_PACKAGES_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm set //npm.pkg.github.com/:_authToken=${{secrets.GH_PACKAGES_TOKEN}}
      - run: npm set @junilearning:registry=https://npm.pkg.github.com/
      - run: npm install
      - run: npm run rewrites
      - name: Changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
      - name: Generate commit
        if: contains(steps.changed-files.outputs.modified_files, 'vercel')
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Updating vercel rewrites.'
